### ISSUE TITLE
Day_38 Workout Tracker HTTPERROR: 400

### ISSUE THREAD

**Issue by Pokealimit** [Pokealimit/Master-Python-100-Projects-100-Days#1]
Been trying to solve the following error when posting to google sheet through sheety:

        raise HTTPError(http_error_msg, response=self)
        requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.sheety.co/xxxxxxxx/myWorkouts/workouts

Done the following below but yet to work:
- [x] Checked sheety app permission in google sheet and have given access to modify sheet.
- [x] Checked column format in google sheet
- [x] Tried sending in string value instead of float

**Comment by Pokealimit** [comment]
turns out parameter have to be singular while the endpoint is plural

https://api.sheety.co/xxxxxxxx/myWorkouts/workouts

          "workout": {
                      "date": only_date,
                      "time": only_time,
                      "exercise": exercise['exercise'],
                      "duration": exercise['duration'],
                      "calories": exercise['calories']
                  }
